// Restaurant data for the prototype.
//
// IMPORTANT CAVEATS (read before using this for anything beyond a click-through demo):
// 1) These are REAL Klang Valley restaurants with REAL addresses, gathered from public food
//    guides (KL Foodie, The Smart Local, SETHLUI, Wanderlog, and similar), so "Open navigation"
//    points to an actual, specific place instead of a generic name+cuisine search.
// 2) `lat`/`lng` are APPROXIMATE, neighborhood-level coordinates (not precise rooftop geocodes),
//    used to compute real distance from the user's actual browser location via the Haversine
//    formula in app.js. Good enough to demo real distance sorting/filtering; swap for precise
//    coordinates once a real geocoding source (Google Places, etc.) is wired in.
// 3) `noPorkLard` and `vegetarian` are HEURISTICS based on cuisine/ownership type (e.g. mamak
//    and Malay nasi kandar stalls marked `noPorkLard: true`), NOT verified certification.
//    Deliberately, there is no "halal" boolean here — halal certification requires JAKIM
//    verification we don't have, so instead of asserting a status we can't back up, the app
//    filters on the more honest, lower-stakes claim ("reported to not serve pork/lard") and
//    surfaces real certification only as a crowdsourced signal (see `communityReports` +
//    the report UI on the detail screen), never as a system-asserted fact.
// 4) `menu` items and prices are illustrative estimates, not pulled from real menus.
// 5) `communityReports` are seeded with small illustrative counts so the reporting feature has
//    something to show on first load; in this prototype, new reports are added in memory only
//    and reset on page reload. A real build persists these per-account via the backend.
// 6) `review` is flavor text framed as an in-app tester comment, not a real review attributed
//    to a real person.
//
// Swap this whole file out once the Google Places API is wired in — keep a compatible shape
// (or adjust buildDeck()/render functions in app.js to match a new one).

const RESTAURANTS = [
  {
    id: "r1",
    name: "Original Kayu Nasi Kandar",
    address: "64, Jalan SS2/10, 47300 Petaling Jaya, Selangor",
    lat: 3.1136,
    lng: 101.6238,
    cuisine: "Malaysian, Nasi Kandar",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7:30am – 11pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#f4a261,#e76f51)",
    menu: [
      { name: "Nasi Kandar (mixed rice)", price: 12 },
      { name: "Ayam Goreng Berempah", price: 8 },
      { name: "Teh Tarik", price: 3 },
    ],
    review: "Always busy, but the queue moves fast and the gravy mix is worth it.",
    communityReports: { noPorkLard: 4, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r2",
    name: "Nasi Kandar Pelita",
    address: "149, Jalan Ampang, 50450 Kuala Lumpur",
    lat: 3.1611,
    lng: 101.7166,
    cuisine: "Malaysian, Nasi Kandar",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "Open 24 hours",
    meals: ["breakfast", "lunch", "dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#e9c46a,#f4a261)",
    menu: [
      { name: "Nasi Kandar Special", price: 10 },
      { name: "Roti Canai", price: 2 },
    ],
    review: "My go-to for a 2am craving — never closes.",
    communityReports: { noPorkLard: 6, halalCert: 2, alcohol: 0 },
  },
  {
    id: "r3",
    name: "Restoran Mohd Yaseem",
    address: "351 & 353, Jalan Tuanku Abdul Rahman, 50100 Kuala Lumpur",
    lat: 3.1637,
    lng: 101.6969,
    cuisine: "Malaysian, Nasi Kandar",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 11pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#f77f00,#d62828)",
    menu: [
      { name: "Nasi Kandar with Squid", price: 14 },
      { name: "Sotong Goreng Tepung", price: 9 },
    ],
    review: "Consistently good — a real institution on this street.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r4",
    name: "Syed Bistro",
    address: "44, Persiaran Ara Kiri, Lucky Garden, 59100 Bangsar, Kuala Lumpur",
    lat: 3.1289,
    lng: 101.6669,
    cuisine: "Malaysian, Nasi Kandar",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍽️",
    gradient: "linear-gradient(135deg,#bc6c25,#606c38)",
    menu: [
      { name: "Nasi Kandar Set", price: 13 },
      { name: "Kari Ikan", price: 10 },
    ],
    review: "A bit pricier than the stalls, but comfortable seating.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r5",
    name: "Sate Kajang Hj Samuri",
    address: "Lot 3764-E, Jalan Saujana, 43000 Kajang, Selangor",
    lat: 2.9931,
    lng: 101.7874,
    cuisine: "Malaysian, Grilled Satay",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "12pm – 10pm",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍢",
    gradient: "linear-gradient(135deg,#bc6c25,#8a3b12)",
    menu: [
      { name: "Sate Ayam (10 sticks)", price: 10 },
      { name: "Nasi Impit", price: 3 },
    ],
    review: "Worth the drive out — the original outlet, not a copycat.",
    communityReports: { noPorkLard: 5, halalCert: 3, alcohol: 0 },
  },
  {
    id: "r6",
    name: "Devi's Corner",
    address: "69, Jalan Telawi 3, Bangsar Baru, 59100 Kuala Lumpur",
    lat: 3.1301,
    lng: 101.6708,
    cuisine: "Indian-Muslim, Mamak",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "Open 24 hours",
    meals: ["breakfast", "lunch", "dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🫓",
    gradient: "linear-gradient(135deg,#f4a261,#2a9d8f)",
    menu: [
      { name: "Roti Canai", price: 2 },
      { name: "Teh Tarik", price: 3 },
    ],
    review: "Classic mamak — good for a 3am roti session with friends.",
    communityReports: { noPorkLard: 3, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r7",
    name: "Sri Steven's Corner (OUG)",
    address: "18 & 18A, Jalan Hujan Rahmat Dua, OUG, 58200 Kuala Lumpur",
    lat: 3.0662,
    lng: 101.6667,
    cuisine: "Indian-Muslim, Mamak",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "Open 24 hours",
    meals: ["breakfast", "lunch", "dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🍳",
    gradient: "linear-gradient(135deg,#e9c46a,#e76f51)",
    menu: [
      { name: "Maggi Goreng", price: 7 },
      { name: "Milo Ais", price: 4 },
    ],
    review: "A proper OUG institution, always packed on weekends.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r8",
    name: "Valentine Roti",
    address: "Store No. 1, Jalan Semarak, 54000 Kuala Lumpur",
    lat: 3.1729,
    lng: 101.7025,
    cuisine: "Indian-Muslim, Roti",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 3am, closed Sundays",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🥞",
    gradient: "linear-gradient(135deg,#f4a261,#f77f00)",
    menu: [
      { name: "Roti Tissue", price: 5 },
      { name: "Teh Ais Limau", price: 4 },
    ],
    review: "Their roti tissue is stupidly tall — good fun for groups.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r9",
    name: "Kafei Dian",
    address: "80, Jalan Panggong, City Centre, 50150 Kuala Lumpur",
    lat: 3.1436,
    lng: 101.6963,
    cuisine: "Chinese, Kopitiam",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 6pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "☕",
    gradient: "linear-gradient(135deg,#8d99ae,#2b2d42)",
    menu: [
      { name: "Kaya Toast Set", price: 7 },
      { name: "Kopi O", price: 3 },
    ],
    review: "Old-school Petaling Street coffee shop, cheap and reliable.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r10",
    name: "Merchant's Lane",
    address: "150, Jalan Petaling, City Centre, 50000 Kuala Lumpur",
    lat: 3.143,
    lng: 101.696,
    cuisine: "Fusion, Cafe",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "9am – 6pm, closed Wed",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down"],
    emoji: "🥗",
    gradient: "linear-gradient(135deg,#40916c,#2d6a4f)",
    menu: [
      { name: "Nyonya Laksa", price: 18 },
      { name: "Iced Gula Melaka Latte", price: 14 },
    ],
    review: "Beautiful shophouse space, good for a slow weekend brunch.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r11",
    name: "Luckin Kopi",
    address: "4, Jalan Panggong, City Centre, 50000 Kuala Lumpur",
    lat: 3.1438,
    lng: 101.6965,
    cuisine: "Chinese, Kopitiam",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "7:30am – 5pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🍮",
    gradient: "linear-gradient(135deg,#6d597a,#355070)",
    menu: [
      { name: "Half-boiled Eggs + Toast", price: 6 },
      { name: "Iced Kopi", price: 4 },
    ],
    review: "Tiny, unassuming, and one of the better kaya toasts around here.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r12",
    name: "Merdekarya",
    address: "352, Jalan 5/57, Bukit Gasing, 46000 Petaling Jaya, Selangor",
    lat: 3.108,
    lng: 101.647,
    cuisine: "Cafe, Comfort Food",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: true,
    hours: "5pm – 12am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🎤",
    gradient: "linear-gradient(135deg,#7209b7,#3a0ca3)",
    menu: [
      { name: "Nasi Lemak Rendang", price: 15 },
      { name: "Craft Beer", price: 20 },
    ],
    review: "Small stage, open-mic nights — very local, very chill.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 3 },
  },
  {
    id: "r13",
    name: "The Social, Bangsar",
    address: "57-59, Jalan Telawi 3, Bangsar, 59100 Kuala Lumpur",
    lat: 3.1301,
    lng: 101.6708,
    cuisine: "Western, Bar",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: true,
    hours: "5pm – 1am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🎸",
    gradient: "linear-gradient(135deg,#264653,#2a9d8f)",
    menu: [
      { name: "Fish & Chips", price: 32 },
      { name: "Craft Beer", price: 22 },
    ],
    review: "Reliable weekend live sets and a decent burger.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 4 },
  },
  {
    id: "r14",
    name: "Ril's Bangsar",
    address: "30, Jalan Telawi 5, Bangsar Baru, 59100 Kuala Lumpur",
    lat: 3.1295,
    lng: 101.6715,
    cuisine: "Western, Steakhouse",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: true,
    hours: "6pm – 1am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🥩",
    gradient: "linear-gradient(135deg,#6a040f,#370617)",
    menu: [
      { name: "Ribeye 250g", price: 88 },
      { name: "House Cocktail", price: 35 },
    ],
    review: "Date-night territory — book ahead on weekends.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r15",
    name: "Alexis Bistro, Great Eastern Mall",
    address: "Lot 10, Great Eastern Mall, 303, Jalan Ampang, 50450 Kuala Lumpur",
    lat: 3.1601,
    lng: 101.7159,
    cuisine: "Western, Wine Bar",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: true,
    hours: "11am – 12am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🍷",
    gradient: "linear-gradient(135deg,#22223b,#4a4e69)",
    menu: [
      { name: "Truffle Fries", price: 24 },
      { name: "Glass of Wine", price: 32 },
    ],
    review: "Jazzy background sets, good for an after-work wind-down.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r16",
    name: "Nature's Vegetarian Restaurant",
    address: "24, Jalan Telawi 3, Bangsar Baru, 59100 Kuala Lumpur",
    lat: 3.1301,
    lng: 101.6708,
    cuisine: "Vegetarian, Chinese",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "11am – 9:30pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🥦",
    gradient: "linear-gradient(135deg,#52b788,#2d6a4f)",
    menu: [
      { name: "Mock Meat Rice Set", price: 12 },
      { name: "Herbal Soup", price: 8 },
    ],
    review: "Surprisingly hearty for an all-veg menu.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r17",
    name: "Loving Cafe Sri Petaling",
    address: "23, Jalan 13/149L, Bandar Baru Sri Petaling, 57000 Kuala Lumpur",
    lat: 3.0654,
    lng: 101.6892,
    cuisine: "Vegetarian, Cafe",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "8am – 5pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🥬",
    gradient: "linear-gradient(135deg,#74c69d,#40916c)",
    menu: [
      { name: "Vegetarian Nasi Lemak", price: 6 },
      { name: "Soy Milk", price: 3 },
    ],
    review: "Good value, and lighter than the usual nasi lemak.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r18",
    name: "Nasi Lemak Alor Corner",
    address: "Changkat Bukit Bintang, 50200 Kuala Lumpur",
    lat: 3.1454,
    lng: 101.7107,
    cuisine: "Malaysian, Nasi Lemak Stall",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 11:30am, Tue–Sun (closed Mon)",
    meals: ["breakfast"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#d62828,#f77f00)",
    menu: [
      { name: "Nasi Lemak Special", price: 6 },
      { name: "Extra Sambal", price: 1 },
    ],
    review: "Been running since 1980 — queue early, it sells out.",
    communityReports: { noPorkLard: 3, halalCert: 1, alcohol: 0 },
  },

  // ---- Added: broader cuisine/geographic spread beyond mamak/nasi kandar ----
  {
    id: "r19",
    name: "Bala's Banana Leaf Rice",
    address: "25, Lorong Ara Kiri 1, Bangsar, 59100 Kuala Lumpur",
    lat: 3.1275,
    lng: 101.6685,
    cuisine: "Indian, Banana Leaf Rice",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#f77f00,#9d0208)",
    menu: [
      { name: "Banana Leaf Rice Set", price: 12 },
      { name: "Mutton Curry", price: 14 },
    ],
    review: "Unlimited rice and veggies, order the fried chicken too.",
    communityReports: { noPorkLard: 3, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r20",
    name: "Sri Ganapathi Mess",
    address: "47, Jalan 1/10, Seksyen 1, 46000 Petaling Jaya, Selangor",
    lat: 3.1073,
    lng: 101.6425,
    cuisine: "Indian, Vegetarian Banana Leaf",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "6:30am – 9pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#ffb703,#fb8500)",
    menu: [
      { name: "Vegetarian Banana Leaf Set", price: 8 },
      { name: "Thosai", price: 3 },
    ],
    review: "Cheap, all-veg, and reliably good curries.",
    communityReports: { noPorkLard: 4, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r21",
    name: "Sri Paandi Restaurant",
    address: "254, Jalan Tun Sambanthan, Brickfields, 50470 Kuala Lumpur",
    lat: 3.128,
    lng: 101.686,
    cuisine: "Indian, Banana Leaf Rice",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10:30pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍽️",
    gradient: "linear-gradient(135deg,#e85d04,#dc2f02)",
    menu: [
      { name: "Fish Head Curry", price: 28 },
      { name: "Banana Leaf Rice Set", price: 13 },
    ],
    review: "Brickfields institution — the fish head curry is the move.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r22",
    name: "QUACKTEOW",
    address: "Lorong Rahim Kajai 14, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    lat: 3.137,
    lng: 101.627,
    cuisine: "Chinese, Char Kuey Teow",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#606c38,#283618)",
    menu: [
      { name: "Char Kuey Teow", price: 8 },
      { name: "Duck Egg Add-on", price: 2 },
    ],
    review: "Smoky wok hei, worth the short wait.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r23",
    name: "Lau Wan Kuetiau Goreng",
    address: "13, Jalan SS 3/33, Taman Universiti, 47300 Petaling Jaya, Selangor",
    lat: 3.108,
    lng: 101.615,
    cuisine: "Chinese, Char Kuey Teow",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🥢",
    gradient: "linear-gradient(135deg,#4a4e69,#22223b)",
    menu: [
      { name: "Kuey Teow Goreng", price: 8 },
      { name: "Cockles Add-on", price: 3 },
    ],
    review: "A PJ hawker classic, go early before it sells out.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r24",
    name: "Pak Teh Char Koay Teow & Nasi Lemak Ayam",
    address: "29, Jalan Selimang, Taman Tenaga, 56000 Cheras, Kuala Lumpur",
    lat: 3.073,
    lng: 101.737,
    cuisine: "Malaysian, Hawker",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "6pm – 1am",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🔥",
    gradient: "linear-gradient(135deg,#e76f51,#e63946)",
    menu: [
      { name: "Halal Char Koay Teow", price: 9 },
      { name: "Nasi Lemak Ayam", price: 9 },
    ],
    review: "Rare halal-owned char koay teow stall, popular for late supper.",
    communityReports: { noPorkLard: 5, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r25",
    name: "Boat Noodle",
    address: "G3A Heritage Lane, Empire Damansara, Damansara Perdana, 47820 Petaling Jaya, Selangor",
    lat: 3.161,
    lng: 101.605,
    cuisine: "Thai, Boat Noodles",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#d62828,#f77f00)",
    menu: [
      { name: "Boat Noodles (per bowl)", price: 3.5 },
      { name: "Thai Iced Tea", price: 6 },
    ],
    review: "Small bowls, easy to keep ordering — fun for groups.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r26",
    name: "Vicchuda Tom Yam",
    address: "24, Jalan SS21/35, Damansara Utama, 47400 Petaling Jaya, Selangor",
    lat: 3.137,
    lng: 101.621,
    cuisine: "Thai",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 12am",
    meals: ["dinner", "supper"],
    vibes: ["sit-down", "spicy"],
    emoji: "🦐",
    gradient: "linear-gradient(135deg,#ef233c,#d90429)",
    menu: [
      { name: "Tom Yam Seafood", price: 22 },
      { name: "Thai Basil Chicken", price: 16 },
    ],
    review: "Proper sour-spicy tom yam, popular with the SS21 crowd.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r27",
    name: "Surisit Thai Kopitiam",
    address: "17, Lorong Rahim Kajai 13, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    lat: 3.138,
    lng: 101.626,
    cuisine: "Thai, Kopitiam",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 4pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🍳",
    gradient: "linear-gradient(135deg,#f4a261,#e9c46a)",
    menu: [
      { name: "Thai Boat Noodles", price: 8 },
      { name: "Thai Milk Tea", price: 5 },
    ],
    review: "Casual TTDI spot, good for a quick Thai breakfast.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r28",
    name: "Thai Somtam Seafood",
    address: "88, Changkat Bukit Bintang, Bukit Bintang, 50200 Kuala Lumpur",
    lat: 3.1445,
    lng: 101.711,
    cuisine: "Thai, Seafood",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 2am",
    meals: ["dinner", "supper"],
    vibes: ["sit-down", "spicy"],
    emoji: "🦀",
    gradient: "linear-gradient(135deg,#c1121f,#780000)",
    menu: [
      { name: "Somtam Papaya Salad", price: 12 },
      { name: "Grilled Seafood Platter", price: 45 },
    ],
    review: "Late-night Thai on Changkat, good after a night out.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r29",
    name: "Southern Rock Seafood",
    address: "32, Jalan Kemuja, Bangsar, 59000 Kuala Lumpur",
    lat: 3.132,
    lng: 101.671,
    cuisine: "Western, Seafood",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6pm – 12am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🦞",
    gradient: "linear-gradient(135deg,#023047,#219ebc)",
    menu: [
      { name: "Half Boston Lobster", price: 68 },
      { name: "Grilled Oysters (half dozen)", price: 32 },
    ],
    review: "Solid choice for a special-occasion seafood dinner.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 3 },
  },
  {
    id: "r30",
    name: "The Fat Fish",
    address: "15-05, Mont Kiara Shoplex, Jalan Kiara, Mont Kiara, 50480 Kuala Lumpur",
    lat: 3.1725,
    lng: 101.651,
    cuisine: "Western, Seafood",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🐟",
    gradient: "linear-gradient(135deg,#0077b6,#00b4d8)",
    menu: [
      { name: "Fish & Chips", price: 34 },
      { name: "Seafood Platter", price: 78 },
    ],
    review: "Mont Kiara family favorite, generous portions.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r31",
    name: "Muhibbah Seafood Restaurant",
    address: "Lot 2851, Jalan Seri Penchala, Kampung Sungai Penchala, 60000 Kuala Lumpur",
    lat: 3.165,
    lng: 101.628,
    cuisine: "Chinese, Seafood",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 12am",
    meals: ["dinner", "supper"],
    vibes: ["sit-down", "spicy"],
    emoji: "🦑",
    gradient: "linear-gradient(135deg,#006466,#144552)",
    menu: [
      { name: "Butter Prawns", price: 38 },
      { name: "Salted Egg Squid", price: 32 },
    ],
    review: "Kampung-style zi char, always crowded on weekends.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r32",
    name: "Pince & Pints",
    address: "32, Jalan Telawi 5, Bangsar, 59100 Kuala Lumpur",
    lat: 3.1298,
    lng: 101.671,
    cuisine: "Western, Seafood Bar",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 1am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🦐",
    gradient: "linear-gradient(135deg,#3a5a40,#344e41)",
    menu: [
      { name: "Snow Crab Boil", price: 58 },
      { name: "Craft Beer", price: 24 },
    ],
    review: "Messy-hands crab boil, fun for a group dinner.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r33",
    name: "Ramen Seirock-ya",
    address: "6-G, Jalan SS21/35, Damansara Utama, 47400 Petaling Jaya, Selangor",
    lat: 3.137,
    lng: 101.6205,
    cuisine: "Japanese, Ramen",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 9:30pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#7f5539,#9c6644)",
    menu: [
      { name: "Tonkotsu Ramen", price: 26 },
      { name: "Gyoza (6pc)", price: 14 },
    ],
    review: "Rich broth, one of the better ramen spots in SS21.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r34",
    name: "Mitsuyado Seimen",
    address: "2nd Floor, The Starling Mall, 6, Jalan SS 21/37, Damansara Utama, 47400 Petaling Jaya, Selangor",
    lat: 3.1345,
    lng: 101.6195,
    cuisine: "Japanese, Ramen",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍥",
    gradient: "linear-gradient(135deg,#6a4c93,#1a659e)",
    menu: [
      { name: "Signature Ramen", price: 28 },
      { name: "Chashu Rice", price: 12 },
    ],
    review: "Mall ramen done well, usually has a short queue.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r35",
    name: "Kuriya Japanese Restaurant",
    address: "Bangsar Shopping Centre, Jalan Maarof, Bukit Bandaraya, 59000 Kuala Lumpur",
    lat: 3.1335,
    lng: 101.667,
    cuisine: "Japanese, Sushi",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍣",
    gradient: "linear-gradient(135deg,#14213d,#003049)",
    menu: [
      { name: "Sushi Omakase Set", price: 88 },
      { name: "Chirashi Don", price: 42 },
    ],
    review: "A step up for a proper sushi dinner, book ahead.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r36",
    name: "Fluffed",
    address: "28, Jalan PJS 8/4, PJS 8, Sunway Mentari, 46150 Petaling Jaya, Selangor",
    lat: 3.072,
    lng: 101.605,
    cuisine: "Dessert, Cafe",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "12pm – 10pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🧁",
    gradient: "linear-gradient(135deg,#ffafcc,#ffc8dd)",
    menu: [
      { name: "Soufflé Pancakes", price: 18 },
      { name: "Matcha Latte", price: 12 },
    ],
    review: "Instagram-famous fluffy pancakes, worth the hype.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r37",
    name: "Foo Foo Classic Desserts",
    address: "64A, Jalan Burhanuddin Helmi, Taman Tun Dr Ismail, 60000 Kuala Lumpur",
    lat: 3.1425,
    lng: 101.624,
    cuisine: "Dessert, Chinese",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "2pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🍮",
    gradient: "linear-gradient(135deg,#fefae0,#e9edc9)",
    menu: [
      { name: "Mango Pomelo Sago", price: 9 },
      { name: "Cheng Tng", price: 7 },
    ],
    review: "Classic TTDI dessert stop after dinner.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r38",
    name: "BASK.",
    address: "APW, 29, Jalan Riong, Bangsar, 59100 Kuala Lumpur",
    lat: 3.1265,
    lng: 101.673,
    cuisine: "Western, Brunch Cafe",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 5pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down"],
    emoji: "🥞",
    gradient: "linear-gradient(135deg,#ffd6a5,#fdffb6)",
    menu: [
      { name: "Eggs Benedict", price: 26 },
      { name: "Flat White", price: 14 },
    ],
    review: "Bright, plant-filled space, popular weekend brunch spot.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r39",
    name: "Paolo Paolo Gelato",
    address: "The Five, Kompleks Pejabat Damansara, 49, Jalan Dungun, Bukit Damansara, 50490 Kuala Lumpur",
    lat: 3.147,
    lng: 101.665,
    cuisine: "Dessert, Italian Gelato",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "11am – 9pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🍨",
    gradient: "linear-gradient(135deg,#f6bd60,#f7ede2)",
    menu: [
      { name: "Gelato (2 scoops)", price: 14 },
      { name: "Affogato", price: 16 },
    ],
    review: "Small-batch gelato, genuinely tastes house-made.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r40",
    name: "Kanna Curry House",
    address: "29, Jalan 17/45, Seksyen 17, 46400 Petaling Jaya, Selangor",
    lat: 3.102,
    lng: 101.628,
    cuisine: "Indian, Banana Leaf Rice",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍗",
    gradient: "linear-gradient(135deg,#9d4edd,#5a189a)",
    menu: [
      { name: "Banana Leaf Rice Set", price: 12 },
      { name: "Butter Chicken", price: 16 },
    ],
    review: "Popular Seksyen 17 spot, generous curry portions.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },

  // r41–r65: Taman Melawati / Wangsa Maju / Setiawangsa area, added after a user
  // living in Taman Melawati pointed out the deck barely covered their neighbourhood.
  // Sourced from Google-indexed local listings (foodpanda, Foursquare, Waze, Yelp),
  // food blogs (Eat Drink KL, Yummy Advisor, Saji.my), and social platforms (TikTok,
  // Lemon8, Threads) rather than just one source, per the user's request.
  {
    id: "r41",
    name: "Lidah Manja (Taman Melawati)",
    address: "318, Lorong Kedah, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2098,
    lng: 101.7521,
    cuisine: "Indonesian, Ayam Gepuk",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 8pm (Fri 2:30pm – 8pm)",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#e63946,#b5171e)",
    menu: [
      { name: "Ayam Gepuk Rempah Perap 1/4", price: 11 },
      { name: "Sambal Tempoyak", price: 3 },
      { name: "Kangkung Goreng", price: 6 },
    ],
    review: "Habanero-level sambal if you want it — good crunch on the fried chicken too.",
    communityReports: { noPorkLard: 3, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r42",
    name: "Polecats Coffee",
    address: "36, Jalan Bandar 1, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2105,
    lng: 101.7548,
    cuisine: "Cafe, Coffee",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 6pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down", "quick-bite"],
    emoji: "☕",
    gradient: "linear-gradient(135deg,#6f4e37,#3c2a21)",
    menu: [
      { name: "Flat White", price: 12 },
      { name: "All-Day Breakfast", price: 18 },
    ],
    review: "Long-running neighbourhood coffee spot, good for a laptop morning.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r43",
    name: "Restoran Raso Omak Den",
    address: "318, Lorong Selangor, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2088,
    lng: 101.7515,
    cuisine: "Indonesian, Minang/Padang",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#c1440e,#7a2e0e)",
    menu: [
      { name: "Rendang Daging", price: 14 },
      { name: "Gulai Ayam", price: 12 },
    ],
    review: "Padang-style rendang, rich and slow-cooked — order early before it sells out.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r44",
    name: "Tim's Teapot Terrace",
    address: "9128, Jalan Bandar 4, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2112,
    lng: 101.7552,
    cuisine: "Cafe, Tea House, Dessert",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["breakfast", "supper"],
    vibes: ["sit-down"],
    emoji: "🍰",
    gradient: "linear-gradient(135deg,#f4978e,#f08080)",
    menu: [
      { name: "High Tea Set", price: 28 },
      { name: "Signature Cheesecake", price: 16 },
    ],
    review: "Pretty terrace seating, nice for a slow afternoon tea catch-up.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r45",
    name: "Nostalgia Kopitiam",
    address: "9163, Jalan Negara, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2125,
    lng: 101.7565,
    cuisine: "Malaysian, Northern-Style Kopitiam",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 6pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#e9c46a,#f4a261)",
    menu: [
      { name: "Laksa Utara", price: 9 },
      { name: "Takua Rendang", price: 8 },
    ],
    review: "Jukebox and vinyl records on the wall, laksa tastes properly Penang-inspired.",
    communityReports: { noPorkLard: 3, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r46",
    name: "KFC Taman Melawati",
    address: "241, Jalan Bandar 13, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.214,
    lng: 101.758,
    cuisine: "Fast Food, Fried Chicken",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 12am",
    meals: ["breakfast", "lunch", "dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🍗",
    gradient: "linear-gradient(135deg,#c8102e,#8b0000)",
    menu: [
      { name: "2-pc Chicken Snack Plate", price: 13 },
      { name: "Zinger Burger", price: 12 },
    ],
    review: "The reliable option when nobody can agree on anything else.",
    communityReports: { noPorkLard: 2, halalCert: 3, alcohol: 0 },
  },
  {
    id: "r47",
    name: "Kedai Ayamas Taman Melawati",
    address: "236, Jalan Bandar 13, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2138,
    lng: 101.7578,
    cuisine: "Fast Food, Fried Chicken",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🍤",
    gradient: "linear-gradient(135deg,#f77f00,#d62828)",
    menu: [
      { name: "Golden Crispy Chicken Set", price: 11 },
      { name: "Ayamas Nuggets", price: 9 },
    ],
    review: "Solid grab-and-go if you're not in the mood for a sit-down meal.",
    communityReports: { noPorkLard: 2, halalCert: 2, alcohol: 0 },
  },
  {
    id: "r48",
    name: "Melawati Nasi Ayam Hainan Singapore & Tom Yam",
    address: "Medan Selera Melawati, Jalan Bandar Melawati, 53100 Kuala Lumpur",
    lat: 3.2118,
    lng: 101.7535,
    cuisine: "Hainanese Chicken Rice, Tom Yam",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 9pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🐔",
    gradient: "linear-gradient(135deg,#ffb703,#fb8500)",
    menu: [
      { name: "Hainanese Chicken Rice", price: 9 },
      { name: "Tom Yam Soup", price: 12 },
    ],
    review: "Food-court favourite — the tom yam has real kick, chicken rice is fragrant.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r49",
    name: "Rot Thai Steamboat & Grill (Wangsa Maju)",
    address: "19, Jalan Maju Ria 2, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.2045,
    lng: 101.732,
    cuisine: "Thai, Steamboat/Hotpot Buffet",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 12am",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#ef476f,#d90429)",
    menu: [
      { name: "Steamboat Buffet (per pax)", price: 40 },
      { name: "Thai BBQ Grill Add-on", price: 10 },
    ],
    review: "Unlimited steamboat and grill for one flat price — go hungry.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r50",
    name: "The Khan Mongolian",
    address: "Off Jalan Genting Klang, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.201,
    lng: 101.728,
    cuisine: "Mongolian BBQ & Steamboat",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🥘",
    gradient: "linear-gradient(135deg,#780000,#c1121f)",
    menu: [
      { name: "Mongolian BBQ Buffet", price: 45 },
      { name: "Steamboat Buffet", price: 42 },
    ],
    review: "Build-your-own stir-fry bowl then hand it to the grill — fun for a change-up.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r51",
    name: "Chizu Melawati Mall",
    address: "Melawati Mall, Jalan Bandar Melawati, 53100 Kuala Lumpur",
    lat: 3.2113,
    lng: 101.7538,
    cuisine: "Japanese Fusion, Cafe",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "quick-bite"],
    emoji: "🍱",
    gradient: "linear-gradient(135deg,#48cae4,#0077b6)",
    menu: [
      { name: "Chizu Baked Rice", price: 19 },
      { name: "Salmon Don", price: 24 },
    ],
    review: "Mall spot but doesn't feel like typical mall food — cheesy baked rice is the move.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r52",
    name: "Santai Cafe Melawati",
    address: "Jalan Bandar Melawati, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.21,
    lng: 101.753,
    cuisine: "Thai, Cafe",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 11pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["sit-down", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#06a77d,#005f56)",
    menu: [
      { name: "Tom Yam Goong", price: 16 },
      { name: "Pad Thai", price: 13 },
    ],
    review: "Casual Thai spot, good for a group that wants to share a spread of dishes.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r53",
    name: "Restaurant Vanggey",
    address: "Jalan Bandar Melawati, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2108,
    lng: 101.7542,
    cuisine: "Indian",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 10pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#e85d04,#9d0208)",
    menu: [
      { name: "Fish Head Curry", price: 22 },
      { name: "Thosai Set", price: 7 },
    ],
    review: "Consistent Indian-Muslim comfort food, thosai is crispy at the edges the way it should be.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r54",
    name: "Madfoon Palace",
    address: "Jalan Bandar Melawati, Taman Melawati, 53100 Kuala Lumpur",
    lat: 3.2116,
    lng: 101.7545,
    cuisine: "Mediterranean, Healthy",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🥙",
    gradient: "linear-gradient(135deg,#588157,#3a5a40)",
    menu: [
      { name: "Chicken Mandi", price: 22 },
      { name: "Hummus & Pita", price: 12 },
    ],
    review: "Fragrant mandi rice, lighter than most of the other options nearby.",
    communityReports: { noPorkLard: 1, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r55",
    name: "Molten Chocolate Cafe",
    address: "Melawati Mall, Jalan Bandar Melawati, 53100 Kuala Lumpur",
    lat: 3.212,
    lng: 101.755,
    cuisine: "Dessert, Belgian Cafe",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: true,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["supper", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍫",
    gradient: "linear-gradient(135deg,#4a2c2a,#7b3f00)",
    menu: [
      { name: "Molten Lava Cake", price: 15 },
      { name: "Belgian Waffle", price: 14 },
    ],
    review: "Go for the lava cake, it actually oozes — not just a marketing photo.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r56",
    name: "Al-Nafoura Restaurant",
    address: "Plaza Wangsa Maju, Jalan 1/27C, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.2038,
    lng: 101.7295,
    cuisine: "Arabic, Middle Eastern",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 11pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍢",
    gradient: "linear-gradient(135deg,#bc6c25,#606c38)",
    menu: [
      { name: "Lamb Mandi", price: 28 },
      { name: "Hummus Platter", price: 14 },
    ],
    review: "Generous lamb portions, popular with groups after Isyak.",
    communityReports: { noPorkLard: 1, halalCert: 2, alcohol: 0 },
  },
  {
    id: "r57",
    name: "Sri Ayutthaya",
    address: "Jalan Wangsa Delima, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.2025,
    lng: 101.729,
    cuisine: "Thai",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍤",
    gradient: "linear-gradient(135deg,#e63946,#f1a208)",
    menu: [
      { name: "Tom Yum Seafood", price: 18 },
      { name: "Thai Basil Chicken", price: 14 },
    ],
    review: "Punchy sour-spicy tom yum, one of the better Thai options in the area.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r58",
    name: "NZ Curry House",
    address: "Jalan Wangsa Delima 11, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.2028,
    lng: 101.7305,
    cuisine: "Malaysian, Mamak",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "24 hours",
    meals: ["breakfast", "lunch", "dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#f4a261,#e76f51)",
    menu: [
      { name: "Roti Canai", price: 2.5 },
      { name: "Nasi Kandar Ayam", price: 11 },
    ],
    review: "24-hour mamak reliability — good for a 2am craving too.",
    communityReports: { noPorkLard: 3, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r59",
    name: "Lamb Shepherd Restaurant",
    address: "Jalan 4/27F, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.205,
    lng: 101.731,
    cuisine: "Chinese Muslim, Lamb Specialties",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 12am",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍖",
    gradient: "linear-gradient(135deg,#6a040f,#370617)",
    menu: [
      { name: "Lamb Soup", price: 18 },
      { name: "Stir-fried Lamb Noodles", price: 16 },
    ],
    review: "Rich lamb soup, popular late-night stop after a movie at the mall.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r60",
    name: "Mali's Corner",
    address: "Platinum Walk, Jalan Langkawi, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.206,
    lng: 101.733,
    cuisine: "Malaysian, Char Kuey Teow & Nasi Lemak",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6pm – 2am",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍳",
    gradient: "linear-gradient(135deg,#283618,#606c38)",
    menu: [
      { name: "Char Kuey Teow", price: 9 },
      { name: "Nasi Lemak Special", price: 8 },
    ],
    review: "Late-night hawker stall, wok hei is on point for a street setup.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r61",
    name: "Burger Bakar Kaw Kaw (Wangsa Maju)",
    address: "Jalan 4A/27A, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.2048,
    lng: 101.7318,
    cuisine: "Western, Flame-Grilled Burgers",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 1am",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🍔",
    gradient: "linear-gradient(135deg,#000000,#3a3a3a)",
    menu: [
      { name: "Kaw Kaw Special Burger", price: 15 },
      { name: "Cheese Fries", price: 9 },
    ],
    review: "Smoky flame-grilled patty, the sauce is the whole reason people queue.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r62",
    name: "Fiske Steakhouse",
    address: "Jalan Enggang, Taman Keramat, 54200 Kuala Lumpur",
    lat: 3.1705,
    lng: 101.7455,
    cuisine: "Western, Steaks & Lamb",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🥩",
    gradient: "linear-gradient(135deg,#432818,#99582a)",
    menu: [
      { name: "Ribeye 300g", price: 68 },
      { name: "Lamb Rack", price: 58 },
    ],
    review: "Neighbourhood steakhouse that doesn't feel overpriced for the portion.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r63",
    name: "Gobang Maju Patin Tempoyak",
    address: "Jalan Seri Rejang 1, Taman Sri Rampai, 53300 Kuala Lumpur",
    lat: 3.2005,
    lng: 101.7235,
    cuisine: "Malaysian, Pahang-Style Fish",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 9pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🐟",
    gradient: "linear-gradient(135deg,#40916c,#1b4332)",
    menu: [
      { name: "Gulai Patin Tempoyak", price: 24 },
      { name: "Ulam-ulaman Set", price: 10 },
    ],
    review: "Distinctive durian-fermented tempoyak gravy — not for everyone, but worth trying once.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r64",
    name: "Rumah Makan Cibiuk",
    address: "Jalan Rampai Maju 1, Taman Sri Rampai, 53300 Kuala Lumpur",
    lat: 3.1998,
    lng: 101.7242,
    cuisine: "Indonesian, Sundanese",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#606c38,#283618)",
    menu: [
      { name: "Ayam Bakar Cibiuk", price: 15 },
      { name: "Sayur Asem", price: 8 },
    ],
    review: "West Javanese comfort food, the sambal is bright and citrusy rather than just hot.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r65",
    name: "Jiran Cafe",
    address: "Jalan 3/27D, Wangsa Maju, 53300 Kuala Lumpur",
    lat: 3.2033,
    lng: 101.7298,
    cuisine: "Western, Pasta & Pizza",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 11pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍝",
    gradient: "linear-gradient(135deg,#457b9d,#1d3557)",
    menu: [
      { name: "Aioli Chicken Pasta", price: 17 },
      { name: "Wood-fired Pizza",price: 26 },
    ],
    review: "Neighbourhood Western cafe, reliable pasta without needing to drive into town.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },

  // r66–r120: Wider Klang Valley expansion, in response to the founder's request to cover
  // the whole Klang Valley, not just central KL / PJ / Bangsar / Kajang and the
  // Melawati–Wangsa Maju corridor. Covers Subang Jaya/USJ, Shah Alam, Puchong, Cheras,
  // Damansara (Bandar Utama / Uptown Damansara / Kota Damansara), Klang town,
  // Kepong/Selayang, Cyberjaya/Putrajaya, Ampang town, and PJ areas not yet covered
  // (Kelana Jaya / PJ Old Town). Sourced from food blogs (KL Foodie, SETHLUI, The Smart
  // Local, Wanderlog, Eat Drink KL, foodadvisor.my), delivery/listing platforms
  // (foodpanda, Foursquare, Yelp, Waze), and mall/venue contact pages for exact addresses.

  // ---- Subang Jaya / USJ ----
  {
    id: "r66",
    name: "Lim Fried Chicken",
    address: "47, Jalan SS 15/4, SS 15, 47500 Subang Jaya, Selangor",
    lat: 3.073,
    lng: 101.586,
    cuisine: "Fast Food, Fried Chicken",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 9pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🍗",
    gradient: "linear-gradient(135deg,#f94144,#f3722c)",
    menu: [
      { name: "LFC Chicken Set", price: 12 },
      { name: "Curry Rice", price: 9 },
    ],
    review: "Cult-favourite fried chicken chain that started right here in SS15 — crispy crust, juicy inside.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r67",
    name: "Uncle Seng Handmade Noodles",
    address: "68, Jalan SS 15/4b, SS 15, 47500 Subang Jaya, Selangor",
    lat: 3.0725,
    lng: 101.5865,
    cuisine: "Chinese, Handmade Noodles",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 9pm, closed Mon",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#43302b,#7f5539)",
    menu: [
      { name: "Handmade Noodles with Minced Pork", price: 10 },
      { name: "Wanton Soup", price: 8 },
    ],
    review: "Noodles pulled fresh in-house — proper springy bite, not the machine-cut stuff.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r68",
    name: "RATA Restaurant",
    address: "25, Jalan SS 15/5a, SS 15, 47500 Subang Jaya, Selangor",
    lat: 3.0735,
    lng: 101.5855,
    cuisine: "Asian Fusion, Western",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍽️",
    gradient: "linear-gradient(135deg,#277da1,#577590)",
    menu: [
      { name: "Truffle Cream Pasta", price: 26 },
      { name: "Grilled Chicken Chop", price: 22 },
    ],
    review: "A reliable SS15 sit-down option when the group can't agree between Asian and Western.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r69",
    name: "Goobne Chicken",
    address: "34, Jalan SS 15/4d, SS 15, 47500 Subang Jaya, Selangor",
    lat: 3.0728,
    lng: 101.587,
    cuisine: "Korean, Fried Chicken",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 10pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍗",
    gradient: "linear-gradient(135deg,#f9844a,#f9c74f)",
    menu: [
      { name: "Oven-Roasted Half Chicken", price: 28 },
      { name: "Yangnyeom Wings", price: 24 },
    ],
    review: "Less greasy than the usual Korean fried chicken spots — the soy garlic glaze is worth it.",
    communityReports: { noPorkLard: 1, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r70",
    name: "Daddy Jo Banana Leaf Restaurant",
    address: "31, Jalan USJ 2/2c, USJ 2, 47600 Subang Jaya, Selangor",
    lat: 3.043,
    lng: 101.581,
    cuisine: "Indian, Banana Leaf Rice",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#e85d04,#dc2f02)",
    menu: [
      { name: "Refillable Banana Leaf Rice Set", price: 10 },
      { name: "Mutton Varuval", price: 15 },
    ],
    review: "Refills come without asking twice — great value for the portion size.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r71",
    name: "The Toast House",
    address: "70, Jalan SS 15/4b, SS 15, 47500 Subang Jaya, Selangor",
    lat: 3.0726,
    lng: 101.5862,
    cuisine: "Cafe, Taiwanese Breakfast",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 3pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🥪",
    gradient: "linear-gradient(135deg,#fca311,#e85d04)",
    menu: [
      { name: "Taiwanese Sandwich Set", price: 12 },
      { name: "Soy Milk", price: 4 },
    ],
    review: "Fluffy Taiwanese-style toast, good grab for a quick SS15 breakfast before work.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },

  // ---- Shah Alam ----
  {
    id: "r72",
    name: "Mozer's",
    address: "DVIDA Business Centre, Jalan Bazar U8/101, Bukit Jelutong, 40150 Shah Alam, Selangor",
    lat: 3.085,
    lng: 101.513,
    cuisine: "Middle Eastern, Syrian",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 11pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🥙",
    gradient: "linear-gradient(135deg,#9c6644,#582f0e)",
    menu: [
      { name: "Chicken Shawarma Platter", price: 24 },
      { name: "Hummus with Pita", price: 14 },
    ],
    review: "Bukit Jelutong's go-to for a Middle Eastern craving, generous meat portions.",
    communityReports: { noPorkLard: 1, halalCert: 2, alcohol: 0 },
  },
  {
    id: "r73",
    name: "South Sea Seafood",
    address: "229, Jalan Dua A, Seksyen U5, 40150 Shah Alam, Selangor",
    lat: 3.09,
    lng: 101.545,
    cuisine: "Chinese, Seafood",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🦞",
    gradient: "linear-gradient(135deg,#023047,#219ebc)",
    menu: [
      { name: "Butter Prawns", price: 36 },
      { name: "Steamed Fish (seasonal)", price: 45 },
    ],
    review: "Solid zi char for a group dinner near i-City, portions are generous.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r74",
    name: "Restoran Meng Kee Char Siew",
    address: "Jalan Pekedai U1/36, Hicom-Glenmarie, 40150 Shah Alam, Selangor",
    lat: 3.087,
    lng: 101.584,
    cuisine: "Chinese, Wanton Noodles",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 4pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#6d4c41,#3e2723)",
    menu: [
      { name: "Char Siew Wanton Mee", price: 10 },
      { name: "Roast Pork Rice", price: 11 },
    ],
    review: "Glazed char siew done right — a Glenmarie office-lunch favourite.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r75",
    name: "Pak Anjang Bariani Johor",
    address: "Jalan Rugby 13/30, Seksyen 13, 40100 Shah Alam, Selangor",
    lat: 3.055,
    lng: 101.545,
    cuisine: "Malaysian, Johor-Style Briyani",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 8pm, closed Mon",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#ffb703,#fb8500)",
    menu: [
      { name: "Nasi Briyani Ayam", price: 13 },
      { name: "Acar Timun", price: 3 },
    ],
    review: "Fragrant Johor-style briyani rice, sells out early so go before noon.",
    communityReports: { noPorkLard: 3, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r76",
    name: "Kueh Cafe Seksyen 13",
    address: "Jalan Renang 13/26, Tadisma Business Park, 40100 Shah Alam, Selangor",
    lat: 3.056,
    lng: 101.543,
    cuisine: "Malaysian, Traditional Kuih & Breakfast",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: true,
    liveMusic: false,
    hours: "7:30am – 2pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🧁",
    gradient: "linear-gradient(135deg,#f4978e,#f8ad9d)",
    menu: [
      { name: "Assorted Kuih Platter", price: 8 },
      { name: "Nasi Lemak Bungkus", price: 5 },
    ],
    review: "Old-school kuih spread, good for grabbing a variety box for the office.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },

  // ---- Puchong ----
  {
    id: "r77",
    name: "Restoran Foo Hing Dim Sum",
    address: "1st Flr, No. 31, 33, 35-G, Jalan Puteri 2/6, Bandar Puteri, 47100 Puchong, Selangor",
    lat: 3.0246,
    lng: 101.6183,
    cuisine: "Chinese, Dim Sum",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6:30am – 2:30pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down"],
    emoji: "🥟",
    gradient: "linear-gradient(135deg,#bb3e03,#ae2012)",
    menu: [
      { name: "Har Gow (3pc)", price: 9 },
      { name: "Char Siew Bao", price: 7 },
    ],
    review: "Trolley-style dim sum, arrive early on weekends before the good baskets run out.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r78",
    name: "Puchong Chettinad Mess",
    address: "11, Jalan Puteri 7/9, Bandar Puteri, 47100 Puchong, Selangor",
    lat: 3.023,
    lng: 101.617,
    cuisine: "Indian, Chettinad Banana Leaf Rice",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#d00000,#9d0208)",
    menu: [
      { name: "Chettinad Chicken Banana Leaf Set", price: 13 },
      { name: "Mutton Chukka", price: 16 },
    ],
    review: "Peppery Chettinad spice profile, noticeably different from the usual banana leaf spots.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r79",
    name: "Warung Cikgu",
    address: "1, Jalan BP 6/7, Bandar Bukit Puchong, 47100 Puchong, Selangor",
    lat: 2.995,
    lng: 101.61,
    cuisine: "Malaysian, Malay",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 10pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#606c38,#283618)",
    menu: [
      { name: "Nasi Campur (mixed rice)", price: 9 },
      { name: "Ayam Masak Merah", price: 7 },
    ],
    review: "Homestyle Malay dishes, changes daily depending on what's fresh that morning.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r80",
    name: "Bumbu Bali",
    address: "18 & 18-1, Persiaran Puteri 1, Bandar Puteri, 47100 Puchong, Selangor",
    lat: 3.025,
    lng: 101.619,
    cuisine: "Indonesian, Balinese",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍢",
    gradient: "linear-gradient(135deg,#7209b7,#560bad)",
    menu: [
      { name: "Bebek Betutu (Balinese Duck)", price: 32 },
      { name: "Sate Lilit", price: 14 },
    ],
    review: "Rare taste of proper Balinese spice paste in the Klang Valley, worth the detour.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r81",
    name: "Yap Chuan Bak Kut Teh",
    address: "53, Jalan Bpu 2, Bandar Puchong Utama, 47100 Puchong, Selangor",
    lat: 3.018,
    lng: 101.625,
    cuisine: "Chinese, Bak Kut Teh",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6:30am – 2pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#432818,#6f4518)",
    menu: [
      { name: "Bak Kut Teh (pork ribs)", price: 16 },
      { name: "Yew Char Kway", price: 3 },
    ],
    review: "Herbal broth is peppery and dark, closes early so go before lunch rush ends.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r82",
    name: "Banh Mi Cafe",
    address: "1, Jalan Puteri 7/10, Bandar Puteri, 47100 Puchong, Selangor",
    lat: 3.0232,
    lng: 101.6172,
    cuisine: "Vietnamese",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "9am – 9pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🥖",
    gradient: "linear-gradient(135deg,#40916c,#1b4332)",
    menu: [
      { name: "Banh Mi Thit Nuong", price: 12 },
      { name: "Vietnamese Iced Coffee", price: 8 },
    ],
    review: "Crusty baguette, fresh pickles — a nice change-up from the usual Puchong hawker food.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },

  // ---- Cheras ----
  {
    id: "r83",
    name: "Chapathi Recipes",
    address: "5, Jalan Menara Gading 1, Taman Connaught, 56000 Kuala Lumpur",
    lat: 3.05,
    lng: 101.746,
    cuisine: "Indian, North Indian",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 11pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🫓",
    gradient: "linear-gradient(135deg,#e76f51,#e63946)",
    menu: [
      { name: "Butter Chapathi Set", price: 9 },
      { name: "Chicken Tikka Masala", price: 14 },
    ],
    review: "North Indian comfort food in the middle of Taman Connaught, the chapathis are soft and fresh.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r84",
    name: "Sun Ming Kee Restaurant",
    address: "137, Jalan Sarjana, Taman Connaught, 56000 Cheras, Kuala Lumpur",
    lat: 3.049,
    lng: 101.7455,
    cuisine: "Chinese",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🥡",
    gradient: "linear-gradient(135deg,#22223b,#4a4e69)",
    menu: [
      { name: "Claypot Tofu", price: 18 },
      { name: "Salted Egg Prawns", price: 28 },
    ],
    review: "Neighbourhood zi char that keeps Taman Connaught regulars coming back.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r85",
    name: "Anne Elizabeth The Deli Restaurant",
    address: "1, Jalan Manis 4, Taman Segar, 56100 Cheras, Kuala Lumpur",
    lat: 3.0846,
    lng: 101.7396,
    cuisine: "Western, Italian",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍝",
    gradient: "linear-gradient(135deg,#457b9d,#1d3557)",
    menu: [
      { name: "Carbonara Pasta", price: 22 },
      { name: "Grilled Lamb Chop", price: 38 },
    ],
    review: "A cosy Taman Segar deli that punches above its weight for Western comfort food.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r86",
    name: "Yakitori Haki",
    address: "34G, Jalan 5/101c, Cheras Business Centre, 56100 Kuala Lumpur",
    lat: 3.075,
    lng: 101.75,
    cuisine: "Japanese, Yakitori",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6pm – 12am",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍢",
    gradient: "linear-gradient(135deg,#6a4c93,#1a659e)",
    menu: [
      { name: "Assorted Skewers (5pc)", price: 20 },
      { name: "Chicken Karaage", price: 16 },
    ],
    review: "Smoky charcoal-grilled skewers, good for a low-key izakaya night in Cheras.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r87",
    name: "Gana Satti Sorru and Shellout Corner",
    address: "A8 Hawker Centre, Taman Ikan Emas, Jalan Jelawat 2, 56000 Cheras, Kuala Lumpur",
    lat: 3.065,
    lng: 101.76,
    cuisine: "Indian, South Indian Seafood",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 12am",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🦐",
    gradient: "linear-gradient(135deg,#e85d04,#9d0208)",
    menu: [
      { name: "Sorru (mini idli) Set", price: 8 },
      { name: "Crab Masala", price: 26 },
    ],
    review: "Hawker-centre South Indian stall, the mini idli sorru is the reason people drive here.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r88",
    name: "Fatt Hei Len Restaurant",
    address: "8, Jalan 30a/119, Taman Taynton View, 56000 Cheras, Kuala Lumpur",
    lat: 3.08,
    lng: 101.735,
    cuisine: "Chinese",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5:30pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🥢",
    gradient: "linear-gradient(135deg,#283618,#606c38)",
    menu: [
      { name: "Kung Pao Chicken", price: 18 },
      { name: "Steamed Egg with Seafood", price: 16 },
    ],
    review: "Taynton View neighbourhood favourite, consistent home-style Chinese cooking.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },

  // ---- Damansara (Bandar Utama / Uptown Damansara / Kota Damansara) ----
  {
    id: "r89",
    name: "Village Park Restaurant",
    address: "5, Jalan SS 21/37, Damansara Utama, 47400 Petaling Jaya, Selangor",
    lat: 3.137,
    lng: 101.621,
    cuisine: "Malaysian, Nasi Lemak",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 8pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#e63946,#f1a208)",
    menu: [
      { name: "Nasi Lemak with Ayam Goreng Berempah", price: 15 },
      { name: "Iced Milo", price: 6 },
    ],
    review: "The nasi lemak that launched a hundred copycats — expect a queue any time of day.",
    communityReports: { noPorkLard: 3, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r90",
    name: "Hot Bird",
    address: "83, Ground Floor, Jalan SS 21/1a, Damansara Utama, 47400 Petaling Jaya, Selangor",
    lat: 3.1375,
    lng: 101.6215,
    cuisine: "Western, Nashville-Style Fried Chicken",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 9:30pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍗",
    gradient: "linear-gradient(135deg,#c1121f,#780000)",
    menu: [
      { name: "Nashville Hot Chicken Sandwich", price: 19 },
      { name: "Cajun Fries", price: 10 },
    ],
    review: "Proper Nashville heat levels, ask for 'hot' only if you actually mean it.",
    communityReports: { noPorkLard: 1, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r91",
    name: "Peranakan Place Signature",
    address: "1 Utama Shopping Centre, 1, Lebuh Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor",
    lat: 3.1503,
    lng: 101.6154,
    cuisine: "Nyonya, Peranakan",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#9d4edd,#5a189a)",
    menu: [
      { name: "Nyonya Laksa", price: 19 },
      { name: "Ayam Pongteh", price: 22 },
    ],
    review: "Rich, tamarind-forward Nyonya flavours — a mall spot that doesn't taste like a mall spot.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r92",
    name: "Wonjo Buanjib BBQ",
    address: "1 Utama Shopping Centre, 1, Lebuh Bandar Utama, Bandar Utama, 47800 Petaling Jaya, Selangor",
    lat: 3.1505,
    lng: 101.6156,
    cuisine: "Korean, BBQ",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🥩",
    gradient: "linear-gradient(135deg,#6a040f,#370617)",
    menu: [
      { name: "Samgyeopsal (pork belly) Set", price: 45 },
      { name: "Kimchi Jjigae", price: 20 },
    ],
    review: "Tabletop grill BBQ, good sharing option after a day of shopping at 1 Utama.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 2 },
  },
  {
    id: "r93",
    name: "Restoran Nasi Al-Lemak",
    address: "Dataran Sunway, 13, Jalan PJU 5/6, Kota Damansara, 47810 Petaling Jaya, Selangor",
    lat: 3.152,
    lng: 101.586,
    cuisine: "Malaysian, Nasi Lemak",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 2pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#d62828,#f77f00)",
    menu: [
      { name: "Nasi Lemak Special", price: 7 },
      { name: "Sambal Sotong", price: 6 },
    ],
    review: "Dataran Sunway morning staple, sambal has real punch for the price.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r94",
    name: "Restoran Good Taste",
    address: "Dataran Sunway, 13, Jalan PJU 5/6, Kota Damansara, 47810 Petaling Jaya, Selangor",
    lat: 3.1522,
    lng: 101.5862,
    cuisine: "Chinese, Wonton Noodles",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 3pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#4a4e69,#22223b)",
    menu: [
      { name: "Wonton Mee (dry)", price: 8 },
      { name: "Char Siew Add-on", price: 4 },
    ],
    review: "Springy noodles and a well-balanced dark sauce — a Kota Damansara regular's order.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },

  // ---- Klang town ----
  {
    id: "r95",
    name: "Choon Guan Hainan Coffee 1956",
    address: "Lorong Amarasegara, Kawasan 12, 42000 Pelabuhan Klang, Selangor",
    lat: 3.0,
    lng: 101.395,
    cuisine: "Chinese, Hainanese Kopitiam",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6am – 5pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "☕",
    gradient: "linear-gradient(135deg,#6f4e37,#3c2a21)",
    menu: [
      { name: "Kaya Butter Toast", price: 5 },
      { name: "Hainan White Coffee", price: 4 },
    ],
    review: "Old Port Klang kopitiam running since 1956, the coffee is roasted properly with butter and sugar.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r96",
    name: "Teluk Pulai Bak Kut Teh",
    address: "Kaw 16, 32, Jalan Batai Laut 5, Taman Intan, 41300 Klang, Selangor",
    lat: 3.015,
    lng: 101.43,
    cuisine: "Chinese, Bak Kut Teh",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 3pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#432818,#99582a)",
    menu: [
      { name: "Bak Kut Teh (mixed parts)", price: 18 },
      { name: "Braised Pig Trotter Rice", price: 12 },
    ],
    review: "Klang is where bak kut teh was born, and this is one of the better versions — dark and peppery.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r97",
    name: "Khunthai Authentic Thai Restaurant",
    address: "14, Jalan Permata 1A/KS 09, Pusat Perniagaan Bestari, 42000 Klang, Selangor",
    lat: 3.01,
    lng: 101.455,
    cuisine: "Thai",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🦐",
    gradient: "linear-gradient(135deg,#ef476f,#d90429)",
    menu: [
      { name: "Tom Yam Talay", price: 24 },
      { name: "Pad Kra Pao", price: 15 },
    ],
    review: "Authentic sour-spicy balance, run by a Thai family rather than a Malaysianised version.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r98",
    name: "Restoran Jai Hind",
    address: "94, Jalan Tengku Kelana, Kawasan 1, 41000 Klang, Selangor",
    lat: 3.043,
    lng: 101.448,
    cuisine: "Indian, Banana Leaf Rice",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 10pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#f77f00,#9d0208)",
    menu: [
      { name: "Banana Leaf Rice Set", price: 10 },
      { name: "Fish Head Curry", price: 24 },
    ],
    review: "Right in the heart of Little India Klang, the curries taste properly home-cooked.",
    communityReports: { noPorkLard: 3, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r99",
    name: "Liang Li Ikan Bakar",
    address: "168, Jalan Chan Ah Choo, Pandamaran, 42000 Pelabuhan Klang, Selangor",
    lat: 3.005,
    lng: 101.39,
    cuisine: "Malaysian, Grilled Fish",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["sit-down", "spicy"],
    emoji: "🐟",
    gradient: "linear-gradient(135deg,#bc6c25,#606c38)",
    menu: [
      { name: "Ikan Bakar (grilled stingray)", price: 22 },
      { name: "Sambal Petai", price: 10 },
    ],
    review: "Smoky charcoal-grilled stingray with proper sambal — worth the trip to Pandamaran.",
    communityReports: { noPorkLard: 1, halalCert: 0, alcohol: 0 },
  },

  // ---- Kepong / Selayang ----
  {
    id: "r100",
    name: "Ah Yap Chicken Rice",
    address: "1175, Jalan Kanan, Desa Jaya, Kepong, 52100 Kuala Lumpur",
    lat: 3.217,
    lng: 101.639,
    cuisine: "Chinese, Hainanese Chicken Rice",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 8pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🐔",
    gradient: "linear-gradient(135deg,#ffb703,#fb8500)",
    menu: [
      { name: "Hainanese Chicken Rice", price: 8 },
      { name: "Roast Chicken Add-on", price: 3 },
    ],
    review: "Fragrant rice and tender poached chicken, a Desa Jaya lunchtime staple.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r101",
    name: "Big Tree Head Mamak",
    address: "Persiaran Mergastua, Kepong Baru, 52100 Kuala Lumpur",
    lat: 3.21,
    lng: 101.635,
    cuisine: "Malaysian, Mamak",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "Open 24 hours",
    meals: ["breakfast", "lunch", "dinner", "supper"],
    vibes: ["quick-bite"],
    emoji: "🫓",
    gradient: "linear-gradient(135deg,#f4a261,#e76f51)",
    menu: [
      { name: "Roti Canai", price: 2.5 },
      { name: "Maggi Goreng", price: 7 },
    ],
    review: "Sits under an actual big tree — a Kepong landmark for late-night roti runs.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r102",
    name: "Sushi Mastro Nikkei",
    address: "Unit 1-1, Fortune Centra, 2, Jalan Metro Perdana 6, Taman Usahawan Kepong, 52100 Kuala Lumpur",
    lat: 3.205,
    lng: 101.628,
    cuisine: "Japanese, Nikkei Sushi",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11:30am – 9:30pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍣",
    gradient: "linear-gradient(135deg,#14213d,#003049)",
    menu: [
      { name: "Nikkei-Style Salmon Roll", price: 24 },
      { name: "Aburi Chirashi", price: 32 },
    ],
    review: "Japanese-Peruvian fusion is an unexpected find tucked away in Kepong.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r103",
    name: "Yee Wen Thai Food",
    address: "3a, Jalan Helang Merah, Kepong Baru Tambahan, 52100 Kuala Lumpur",
    lat: 3.213,
    lng: 101.636,
    cuisine: "Thai",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#c1121f,#780000)",
    menu: [
      { name: "Thai Style Kuey Teow", price: 9 },
      { name: "Tom Yum Soup", price: 10 },
    ],
    review: "Street-side Thai stall in Kepong Baru, punchy chili paste on everything.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r104",
    name: "Golek-Golek Suasana Kampung",
    address: "Lot 2074, Lingkaran Tengah 2, KM10, Gombak, 68100 Batu Caves, Selangor",
    lat: 3.245,
    lng: 101.685,
    cuisine: "Malaysian, Grilled Seafood",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "12pm – 11pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🦀",
    gradient: "linear-gradient(135deg,#e85d04,#9d0208)",
    menu: [
      { name: "Grilled Fish with Petai Sambal", price: 24 },
      { name: "Tiger Prawn Milk Curry", price: 32 },
    ],
    review: "Kampung-style open-air setting near Gombak, worth the drive up from Selayang.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },

  // ---- Cyberjaya / Putrajaya ----
  {
    id: "r105",
    name: "Soi 55 Thai Kitchen",
    address: "G-20, The Sphere Atelier Centre, Jalan Atelier 3, Cyber 11, 63000 Cyberjaya, Selangor",
    lat: 2.928,
    lng: 101.643,
    cuisine: "Thai",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "12pm – 11pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#ef476f,#d90429)",
    menu: [
      { name: "Tom Yam Goong", price: 18 },
      { name: "Pad Thai Goong", price: 16 },
    ],
    review: "Cyberjaya office crowd favourite for a spicy weekday lunch.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r106",
    name: "Harley's Burger and Roaster",
    address: "Third Avenue, Jalan Teknokrat 3, Cyber 4, 63000 Cyberjaya, Selangor",
    lat: 2.918,
    lng: 101.652,
    cuisine: "Western, Burgers",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍔",
    gradient: "linear-gradient(135deg,#000000,#3a3a3a)",
    menu: [
      { name: "Smoked Beef Brisket Burger", price: 24 },
      { name: "Roasted Chicken Half", price: 26 },
    ],
    review: "Known locally for one of the better halal-friendly burger patties in Cyberjaya.",
    communityReports: { noPorkLard: 1, halalCert: 2, alcohol: 0 },
  },
  {
    id: "r107",
    name: "Balqis Restaurant",
    address: "8C1, Jalan P8E2/10, Promenade 8, Presint 8, 62250 Putrajaya",
    lat: 2.943,
    lng: 101.689,
    cuisine: "Middle Eastern, Yemeni",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 11pm",
    meals: ["lunch", "dinner", "supper"],
    vibes: ["sit-down"],
    emoji: "🍛",
    gradient: "linear-gradient(135deg,#9c6644,#582f0e)",
    menu: [
      { name: "Mandi Lamb", price: 32 },
      { name: "Aseeda", price: 12 },
    ],
    review: "Yemeni mandi with tender slow-cooked lamb, popular with Putrajaya's civil servant crowd.",
    communityReports: { noPorkLard: 2, halalCert: 3, alcohol: 0 },
  },
  {
    id: "r108",
    name: "Padi House",
    address: "Galeria PJH, Presint 4, 62100 Putrajaya",
    lat: 2.928,
    lng: 101.69,
    cuisine: "Malaysian, Rice Bowls",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "8am – 6pm, closed weekends",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🍚",
    gradient: "linear-gradient(135deg,#606c38,#283618)",
    menu: [
      { name: "Rendang Rice Bowl", price: 14 },
      { name: "Sambal Sotong Rice Bowl", price: 13 },
    ],
    review: "Fast, tidy rice-bowl format aimed at Putrajaya's lunchtime office rush.",
    communityReports: { noPorkLard: 1, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r109",
    name: "Cili Kampung",
    address: "Lot G91, Ground Floor, Alamanda Shopping Centre, Presint 1, 62000 Putrajaya",
    lat: 2.926,
    lng: 101.671,
    cuisine: "Malaysian, Malay",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#d62828,#f77f00)",
    menu: [
      { name: "Nasi Campur Kampung", price: 15 },
      { name: "Ikan Goreng Sambal", price: 10 },
    ],
    review: "Reliable mall spot for traditional kampung-style dishes, good variety of sides.",
    communityReports: { noPorkLard: 1, halalCert: 1, alcohol: 0 },
  },

  // ---- Ampang (broader Ampang town) ----
  {
    id: "r110",
    name: "Sweetree Restaurant",
    address: "12 L1 & 13 L1, L2, Jalan Ampang Putra, Taman Putra Sulaiman, 68000 Ampang, Selangor",
    lat: 3.15,
    lng: 101.755,
    cuisine: "Korean",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍢",
    gradient: "linear-gradient(135deg,#f9844a,#f9c74f)",
    menu: [
      { name: "Kimchi Jjigae Set", price: 22 },
      { name: "Bibimbap", price: 18 },
    ],
    review: "Long-running Korean spot in Ampang's small Koreatown pocket.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 1 },
  },
  {
    id: "r111",
    name: "Kim Kee Nasi Ayam Hainan",
    address: "1, Jalan Kolam Air Lama, Taman Dato Ahmad Razali, 68000 Ampang, Selangor",
    lat: 3.145,
    lng: 101.75,
    cuisine: "Chinese, Hainanese Chicken Rice",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "10am – 8pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🐔",
    gradient: "linear-gradient(135deg,#ffb703,#fb8500)",
    menu: [
      { name: "Hainanese Chicken Rice", price: 9 },
      { name: "Steamed Chicken Half", price: 20 },
    ],
    review: "Silky poached chicken with fragrant rice, a well-loved Ampang lunch spot.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r112",
    name: "Uncle Aru's Tandoori Hut",
    address: "449-G, Jalan 5, One Ampang Avenue, 68000 Ampang, Selangor",
    lat: 3.148,
    lng: 101.756,
    cuisine: "Indian, Tandoori",
    priceTier: 2,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 11pm",
    meals: ["dinner", "supper"],
    vibes: ["sit-down", "spicy"],
    emoji: "🍗",
    gradient: "linear-gradient(135deg,#e85d04,#dc2f02)",
    menu: [
      { name: "Tandoori Chicken (half)", price: 18 },
      { name: "Garlic Naan", price: 5 },
    ],
    review: "Charred, smoky tandoori chicken — a popular supper stop in One Ampang Avenue.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r113",
    name: "Nasi Cikgu Sue",
    address: "G-3A, Dagang Avenue, Jalan Dagang B/3a, Taman Dagang, 68000 Ampang, Selangor",
    lat: 3.1467,
    lng: 101.759,
    cuisine: "Malaysian, Kelantanese",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 8pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🌶️",
    gradient: "linear-gradient(135deg,#c1440e,#7a2e0e)",
    menu: [
      { name: "Nasi Kerabu Set", price: 12 },
      { name: "Ayam Percik", price: 8 },
    ],
    review: "East-coast Kelantanese flavours, the blue rice and ulam spread is the draw.",
    communityReports: { noPorkLard: 2, halalCert: 1, alcohol: 0 },
  },
  {
    id: "r114",
    name: "ROLLO Mexican Food",
    address: "G, Dagang Avenue Food Court, Jalan Dagang B/3a, Taman Dagang, 68000 Ampang, Selangor",
    lat: 3.1468,
    lng: 101.7592,
    cuisine: "Mexican",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 9pm",
    meals: ["lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "🌮",
    gradient: "linear-gradient(135deg,#277da1,#577590)",
    menu: [
      { name: "Beef Burrito", price: 16 },
      { name: "Loaded Nachos", price: 14 },
    ],
    review: "Food-court stall doing Mexican food, a nice change from the usual Ampang lineup.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r115",
    name: "Solh Restaurant & Bar",
    address: "Jalan Damai, Off Jalan Ampang, 55000 Kuala Lumpur",
    lat: 3.16,
    lng: 101.735,
    cuisine: "Mediterranean, Bar",
    priceTier: 3,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "5pm – 1am",
    meals: ["dinner"],
    vibes: ["sit-down"],
    emoji: "🍷",
    gradient: "linear-gradient(135deg,#588157,#3a5a40)",
    menu: [
      { name: "Mixed Mezze Platter", price: 38 },
      { name: "Grilled Lamb Kofta", price: 42 },
    ],
    review: "Relaxed Mediterranean small plates and cocktails, popular for after-work drinks near Jalan Ampang.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 3 },
  },

  // ---- PJ areas not yet covered (Kelana Jaya / PJ Old Town) ----
  {
    id: "r116",
    name: "Kim Lian Kee Hokkien Mee",
    address: "Lot 31, Level 2, Paradigm Mall, 1, Jalan SS 7/26A, 47301 Petaling Jaya, Selangor",
    lat: 3.0833,
    lng: 101.598,
    cuisine: "Chinese, Hokkien Mee",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "11am – 10pm",
    meals: ["lunch", "dinner"],
    vibes: ["sit-down"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#3e2723,#5d4037)",
    menu: [
      { name: "Charcoal Fried Hokkien Mee", price: 16 },
      { name: "Crispy Pork Lard Add-on", price: 4 },
    ],
    review: "The famous charcoal wok-hei Hokkien mee, now in a mall food court format.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r117",
    name: "Ming Kee Bak Kut Teh",
    address: "Jalan 1/12, PJ Old Town, 46000 Petaling Jaya, Selangor",
    lat: 3.1073,
    lng: 101.648,
    cuisine: "Chinese, Bak Kut Teh",
    priceTier: 2,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6:30am – 3pm",
    meals: ["breakfast", "lunch"],
    vibes: ["sit-down"],
    emoji: "🍲",
    gradient: "linear-gradient(135deg,#432818,#99582a)",
    menu: [
      { name: "Bak Kut Teh Set", price: 17 },
      { name: "Braised Mushroom with Pork", price: 15 },
    ],
    review: "A PJ Old Town institution for bak kut teh, the broth is rich without being overly salty.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r118",
    name: "Nam Chuan Hainan Kopitiam",
    address: "8, 10 & 12, Jalan SS 6/8, SS 6, 47301 Petaling Jaya, Selangor",
    lat: 3.09,
    lng: 101.603,
    cuisine: "Chinese, Kopitiam / Tai Chow",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "6:30am – 10pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["quick-bite"],
    emoji: "☕",
    gradient: "linear-gradient(135deg,#6f4e37,#3c2a21)",
    menu: [
      { name: "Braised Pork Rice", price: 10 },
      { name: "Wanton Mee", price: 9 },
    ],
    review: "Multiple hawker stalls under one roof in Kelana Jaya's SS6, good for a group with different cravings.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r119",
    name: "Asian Rice Pot",
    address: "11, Jalan SS 5a/11, Kelana Jaya, 47301 Petaling Jaya, Selangor",
    lat: 3.087,
    lng: 101.601,
    cuisine: "Indian, Thosai & Biryani",
    priceTier: 1,
    noPorkLard: true,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 11pm",
    meals: ["breakfast", "lunch", "dinner"],
    vibes: ["quick-bite", "spicy"],
    emoji: "🫓",
    gradient: "linear-gradient(135deg,#ffb703,#fb8500)",
    menu: [
      { name: "Thosai Set", price: 6 },
      { name: "Chicken Biryani", price: 13 },
    ],
    review: "Crispy thosai and fragrant biryani, a Kelana Jaya SS5 favourite for over a decade.",
    communityReports: { noPorkLard: 2, halalCert: 0, alcohol: 0 },
  },
  {
    id: "r120",
    name: "Yue Wei Kopitiam",
    address: "31, Jalan Penchala, 46050 Petaling Jaya, Selangor",
    lat: 3.165,
    lng: 101.628,
    cuisine: "Chinese, Curry Mee",
    priceTier: 1,
    noPorkLard: false,
    vegetarian: false,
    liveMusic: false,
    hours: "7am – 2pm",
    meals: ["breakfast", "lunch"],
    vibes: ["quick-bite"],
    emoji: "🍜",
    gradient: "linear-gradient(135deg,#e63946,#b5171e)",
    menu: [
      { name: "Curry Mee", price: 8 },
      { name: "Minced Pork Meehoon", price: 9 },
    ],
    review: "Coconut-rich curry mee broth, a Jalan Penchala kopitiam worth the small detour.",
    communityReports: { noPorkLard: 0, halalCert: 0, alcohol: 0 },
  },
];

// Fallback reference point (central KL / KLCC) used when browser geolocation is
// unavailable or denied, so distance can still be computed. Clearly a placeholder —
// real distance always requires the user's actual location.
const DEFAULT_COORDS = { lat: 3.1579, lng: 101.7116 };
